name: Build_x86_64

on: [push]

jobs:
  build:
    runs-on: ubuntu:latest
    steps:
      - run: echo VVV:`uname -a`
      - name: Checkout core
        uses: actions/checkout@v3
      - run: ls -l ./